#+title: Lord of the Rings Campaign Notes
* Beginning of Adventure
** Bree: The Town of Beginnings
*** The Prancing Pony
*** The Town Notice Board
**** Sundry Notices and Personals
/"Between the many banal requests for farm hands, errand runners, and love-seekers, there are a few outstanding small writs for those willing to prospect for opportunities./

If a party decides to roll *Investigation, Perception, or Insight* checks while at the notice board, reveal these quests to the party as more adventuring fare.

***** A Delivery Gone Awry
***** The Local Harvest Festival
***** A Lady's Needs
**** A Farmer's Request
*Posted By:* Geoff Haywood

*Location:* Haywood Farm

#+BEGIN_VERSE
To Whomever takes up this writ,
See me at my farmhouse, a day's journey to the Northwest of Bree in the fields of the Lone Lands, the building with a red thatch roof.
Something has killed half of my herd and nearly clawed my son's arm off while he was shepherding in the pastures.
He said it was a massive beast with glowing red eyes and shimmering claws, it ran off toward Allen's Gully to the West of the farm.
I am a wizened man, unable to take on a sheep, let alone some fell beast.
I don't have much, however I will give what I can.

-- Geoff, Farmer of Bree
#+END_VERSE

*Reward:* Five Silver
**** Dark Riders's Rumors
*Posted By:* Celendwil

*Location:* The Crossroads to the North Downs

#+BEGIN_VERSE
Grim Tidings to those of the Bree Lands,
Whilst hunting and travelling the southern fields of the Downs, I had spied dark riders making their ways to south of my favored grounds.
Normally, I have no fears in the fields here, yet the sight of these figures sent a chill to my heart and sent me away in flight.
They had a fell appearance, darkness followed them and moonlight flooded in behind their tracks, perhaps they are heralds of some dark lord.
Should you find out anything of substance or chase these spectres from our lands, come to the Northern Downs, I will find you.
Best of luck, and good hunting.

-- Celendwil
#+END_VERSE

*Reward:* +2 Silver+, *Death*
**** A Bandit's Trade
*Posted By:* William Nailsmith

*Location:* Bree Smith's Shop

#+BEGIN_VERSE
Hail,
While making my way home from a routine travail to Stow for ore so that I may ply my trade bandits fell upon me.
Bastards robbed me of nearly all but my life, I scarcely convinced them to let me keep my shirt.
Be wary along the western ways, those sons-of-whores jump out from the swells in the plains, just out of sight.
Should you find them, do what you will, they are no better than wolves, just don't forget my iron.
I'll make you a piece or two for your efforts, if justice isn't enough.
#+END_VERSE

*Reward:* A custom piece from the smith
